# 一个简单的 GitHub Pages 部署工作流
name: Deploy static content to Pages

on:
  # 仅在推送到默认分支时运行
  push:  # 指定触发事件
    branches:
      - main  # 指定触发 action 的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 安装依赖并构建
        run: |
          npm install
          npm run build

      # 在部署目录中生成 .nojekyll
      - name: 禁用 Jekyll 处理
        run: echo '' > dist/.nojekyll

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.COMPILER_HELPER }}
          BRANCH: gh-pages
          FOLDER: dist

